project:
  type: book
  output-dir: docs
  preview:
    watch-inputs: true

book:
  title: "Mathématiques discrètes"
  output-file: "mathematiques-discretes"
  author: "Marc-André Désautels"
  reader-mode: true
  repo-url: https://github.com/desautm/mathdiscretes
  repo-actions: [edit]
  downloads: [pdf]
  sharing: [twitter, facebook]
  cover-image: triangle_pascal_fibonacci.jpg
  chapters:
    - index.qmd
    - systeme_numeration_v2.qmd
    - representation_nombres_ordinateurs.qmd
    - logique.qmd
    - ensembles.qmd
    - fonctions.qmd
    - notation_grand_o.qmd
    - algorithmes.qmd
    - theorie_nombres.qmd
    - preuves.qmd
    - denombrement.qmd
    - graphes.qmd
    - arbres.qmd
    - references.qmd

comments: 
  hypothesis: true

bibliography: references.bib

highlight-style: pygments

format:
  html:
    theme: cosmo
    code-copy: true
    page-layout: full
  pdf:
    documentclass: scrbook
    keep-tex: false
    code-block-bg: "#d5d6db"
    include-in-header:
      - macros.tex
    geometry:
      - paper=a4paper
      - top=2cm
      - bottom=2cm
      - left=1.5cm
      - right=3.5cm
      - marginparwidth=2.5cm
      - marginparsep=2.5mm
      - twoside

code-fold: false
