# On peut mélanger du code R, Python et Tikz!!

## R

```{r}
#| label: fig-airquality
#| fig-cap: Temperature and ozone level.
#| warning: false

library(ggplot2)

ggplot(airquality, aes(Temp, Ozone)) + 
  geom_point() + 
  geom_smooth(method = "loess"
)
```

## Python

```{python}
#| label: fig-polar
#| fig-cap: "A line plot on a polar axis"

import numpy as np
import matplotlib.pyplot as plt

r = np.arange(0, 2, 0.01)
theta = 2 * np.pi * r
fig, ax = plt.subplots(
  subplot_kw = {'projection': 'polar'} 
)
ax.plot(theta, r)
ax.set_rticks([0.5, 1, 1.5, 2])
ax.grid(True)
plt.show()
```

## Tikz

```{r, engine='tikz'}
\usetikzlibrary{calc}
\begin{tikzpicture}[scale=1]

\draw[-stealth] (-0.5,0)--++(4,0) node[below] {$x$};
\draw[-stealth] (0,-0.5)--++(0,3) node[left] {$y$};
\draw[thick, blue] (-0.25,1.75)--(3.25,-0.25);

\draw (0.6,{-0.6*4/7+45/28})--++($0.015*(4,7)$)--++($0.015*(-7,4)$);
\draw[-stealth, thick, red] (0.5,{-0.5*4/7+45/28}) --++($0.1*(4,7)$) node[right] {\small{$\vec n = (a;b)$}};
\draw[fill=black] (0.5,{-0.5*4/7+45/28}) circle (1pt) node[below] {\small{$(x_0;y_0)$}};
\draw[fill=black] (0,{45/28}) circle (1pt) node[below left] {\small{$-\frac{c}{b}$}};

\draw[-stealth, thick, black] (0.5,{-0.5*4/7+45/28}) --++($-0.2*(-7,4)$) node[above right] {\small{$(x;y)$}};
\draw[fill=black] (1.9,{-1.9*4/7+45/28}) circle (1pt);

\node at (2,-0.75) {\small{$\vec n \cdot (x-x_0;y-y_0)=0$}};
\node at (2,-1.5) {\small{$ax+by+\underbrace{(-ax_0-by_0)}_{=c}=0$}};

\end{tikzpicture}
```