<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mathématiques discrètes - 2&nbsp; Représentation des nombres dans l’ordinateur</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./logique.html" rel="next">
<link href="./systeme_numeration_v2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Aucun résultat",
    "search-matching-documents-text": "documents identiques",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./representation_nombres_ordinateurs.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Représentation des nombres dans l'ordinateur</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Mathématiques discrètes</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/desautm/mathdiscretes" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="./mathematiques-discretes.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
              <i class="bi bi-bi-facebook pe-1"></i>
            Facebook
            </a>
          </li>
      </ul>
    </div>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Préface</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./systeme_numeration_v2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Systèmes de numération positionnelle</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./representation_nombres_ordinateurs.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Représentation des nombres dans l’ordinateur</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Logique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ensembles.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Théorie des ensembles</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fonctions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Fonctions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notation_grand_o.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Notation grand O</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./algorithmes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Introduction aux algorithmes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./theorie_nombres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Théorie des nombres</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preuves.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Preuves et raisonnement mathématique</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./denombrement.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Dénombrement</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graphes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Graphes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./arbres.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Arbres</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Références</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#représentation-des-entiers" id="toc-représentation-des-entiers" class="nav-link active" data-scroll-target="#représentation-des-entiers"><span class="header-section-number">2.1</span> Représentation des entiers</a>
  <ul class="collapse">
  <li><a href="#entiers-non-signés" id="toc-entiers-non-signés" class="nav-link" data-scroll-target="#entiers-non-signés"><span class="header-section-number">2.1.1</span> Entiers non signés</a></li>
  <li><a href="#entiers-signés" id="toc-entiers-signés" class="nav-link" data-scroll-target="#entiers-signés"><span class="header-section-number">2.1.2</span> Entiers signés</a></li>
  </ul></li>
  <li><a href="#format-dun-nombre-en-virgule-flottante" id="toc-format-dun-nombre-en-virgule-flottante" class="nav-link" data-scroll-target="#format-dun-nombre-en-virgule-flottante"><span class="header-section-number">2.2</span> Format d’un nombre en virgule flottante</a>
  <ul class="collapse">
  <li><a href="#format-général" id="toc-format-général" class="nav-link" data-scroll-target="#format-général">Format général</a></li>
  <li><a href="#opérations-sur-les-nombres-en-virgule-flottante" id="toc-opérations-sur-les-nombres-en-virgule-flottante" class="nav-link" data-scroll-target="#opérations-sur-les-nombres-en-virgule-flottante"><span class="header-section-number">2.2.1</span> Opérations sur les nombres en virgule flottante</a></li>
  </ul></li>
  <li><a href="#sec-ieee754" id="toc-sec-ieee754" class="nav-link" data-scroll-target="#sec-ieee754"><span class="header-section-number">2.3</span> La norme IEEE754</a>
  <ul class="collapse">
  <li><a href="#biais-de-lexposant" id="toc-biais-de-lexposant" class="nav-link" data-scroll-target="#biais-de-lexposant">Biais de l’exposant</a></li>
  <li><a href="#exceptions" id="toc-exceptions" class="nav-link" data-scroll-target="#exceptions">Exceptions</a></li>
  <li><a href="#le-format-à-virgule-flottante-à-précision-simple" id="toc-le-format-à-virgule-flottante-à-précision-simple" class="nav-link" data-scroll-target="#le-format-à-virgule-flottante-à-précision-simple"><span class="header-section-number">2.3.1</span> Le format à virgule flottante à précision simple</a></li>
  <li><a href="#le-format-à-virgule-flottante-à-précision-double" id="toc-le-format-à-virgule-flottante-à-précision-double" class="nav-link" data-scroll-target="#le-format-à-virgule-flottante-à-précision-double"><span class="header-section-number">2.3.2</span> Le format à virgule flottante à précision double</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/desautm/mathdiscretes/edit/main/representation_nombres_ordinateurs.qmd" class="toc-action">Éditez cette page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Représentation des nombres dans l’ordinateur</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Lorsque nous voulons représenter des nombres dans un ordinateur, il faut distinguer deux cas biens différents; la représentation des nombres <strong>entiers</strong> et la représentation des nombres <strong>fractionnaires</strong>.</p>
<section id="représentation-des-entiers" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="représentation-des-entiers"><span class="header-section-number">2.1</span> Représentation des entiers</h2>
<p>En <code>Python</code>, contrairement à la plupart des langages informatiques, les entiers sont représentés avec une précision <strong>infinie</strong>. C’est-à-dire que la seule limite correspond à la mémoire interne de la machine que vous utilisez. Cependant, dans la majorité des langages informatiques, la précision de la représentation des entiers est <strong>finie</strong>, c’est-à-dire qu’un certain nombre de bits est alloué en mémoire pous stocker votre nombre et vous ne pouvez pas le dépasser.</p>
<p>Nous pouvons connaître le nombre de bits utilisés par <code>Python</code> dans la représentation d’un entier en utilisant la fonction <code>getsizeof</code> du module <code>sys</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sys <span class="im">import</span> getsizeof</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>n1 <span class="op">=</span> <span class="dv">2</span><span class="op">**</span><span class="dv">32</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>n2 <span class="op">=</span> <span class="dv">2</span><span class="op">**</span><span class="dv">128</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(getsizeof(n1), getsizeof(n2))</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>32 44</code></pre>
</div>
</div>
<p>Pour étudier le comportement d’entiers ayant une taille fixe, on peut utiliser le module <code>numpy</code>. Ce module possède plusieurs classes d’entiers à taille fixe.</p>
<section id="entiers-non-signés" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="entiers-non-signés"><span class="header-section-number">2.1.1</span> Entiers non signés</h3>
<div id="def-entiers-non-signes" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 2.1 (Entiers non signés (nombres positifs)) </strong></span>Un nombre <strong>entier non signé</strong> (positif) est représenté par un nombre de bits préalablement fixé. Au besoin, on complète le nombre par des zéros à gauche fin d’avoir le nombre total de bits choisi.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Les entiers non signés à taille fixe en <code>Python</code>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><code>numpy.ubyte</code>: entier non signé sur 8 bits</li>
<li><code>numpy.ushort</code>: entier non signé sur 16 bits</li>
<li><code>numpy.uintc</code>: entier non signé sur 32 bits</li>
<li><code>numpy.uint</code>: entier non signé sur 64 bits</li>
</ul>
</div>
</div>
<div id="exm-entiers-non-signes" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.1 </strong></span>Transformez les entiers décimaux suivants en entiers non signés sur un octet (huit bits).</p>
<ol type="a">
<li>143</li>
<li>15</li>
<li>30</li>
</ol>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">bin</span>(np.ubyte(<span class="dv">143</span>)), <span class="bu">bin</span>(np.ubyte(<span class="dv">15</span>)), <span class="bu">bin</span>(np.ubyte(<span class="dv">30</span>)))</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0b10001111 0b1111 0b11110</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Soyez prudents!
</div>
</div>
<div class="callout-body-container callout-body">
<p>Si on tente d’écrire un nombre entier qui dépasse la capacité du format, nous n’obtenons pas nécessairement un message d’erreur, il faut donc être très prudents. Par exemple, le format <code>numpy.byte</code> peut représenter les entiers de 0 à 255. Si nous tentons de représenter 256, nous obtenons:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(np.uint8(<span class="dv">256</span>))</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0</code></pre>
</div>
</div>
</div>
</div>
<p>Ce genre d’erreur est appelée un dépassement d’entier. Un dépassement d’entier (<em>integer overflow</em>) est, en informatique, une condition qui se produit lorsqu’une opération mathématique produit une valeur numérique supérieure à celle représentable dans l’espace de stockage disponible. Par exemple, l’ajout d’une unité au plus grand nombre pouvant être représenté entraîne un dépassement d’entier.</p>
<p>Le dépassement d’entier le plus célèbre de ces dernières années est très probablement celui qui causa la destruction de la fusée <a href="https://www.wikiwand.com/fr/Ariane_5">Ariane 5</a>, lors de son <a href="https://www.wikiwand.com/fr/Vol_501_d'Ariane_5">vol inaugural</a>, le 4 juin 1996.</p>
<div id="exm-plus-grand-entier-non-signe" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.2 </strong></span>Quel est le plus grand entier non signé pouvant être représenté avec:</p>
<ol type="a">
<li>8 bits?</li>
<li>32 bits?</li>
<li><span class="math inline">\(n\)</span> bits?</li>
</ol>
</div>
</section>
<section id="entiers-signés" class="level3" data-number="2.1.2">
<h3 data-number="2.1.2" class="anchored" data-anchor-id="entiers-signés"><span class="header-section-number">2.1.2</span> Entiers signés</h3>
<p>Pour travailler avec des entiers qui peuvent être positifs ou négatifs, il faut inclure le signe du nombre dans sa représentation, et l’on parle alors d’entiers signés.</p>
<div id="def-entiers-signes" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 2.2 (Entiers signés (représentation signe et module)) </strong></span>Un nombre <strong>entier signé</strong> (généralement représenté dans un octet) est un nombre où le 1<sup>er</sup> bit (à gauche) est réservé au signe, et les autres bits permettent d’indiquer la valeur absolue du nombre. Pour indiquer qu’un nombre est positif (+), le 1<sup>er</sup> bit est <code>0</code>, et pour un nombre négatif (-), le 1<sup>er</sup> bit est <code>1</code>.</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Les entiers signés à taille fixe en <code>Python</code>
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li><code>numpy.byte</code>: entier signé sur 8 bits</li>
<li><code>numpy.short</code>: entier signé sur 16 bits</li>
<li><code>numpy.intc</code>: entier signé sur 32 bits</li>
<li><code>numpy.int_</code>: entier signé sur 64 bits</li>
</ul>
</div>
</div>
<div id="exm-completion-tableau-signe-module-4-bits" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.3 </strong></span>Complétez les tableaux suivants qui indiquent la représentation signe et module sur 4 bits.</p>
<div class="columns">
<div class="column" style="width:40%;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Base 2</strong></th>
<th style="text-align: center;"><strong>Base 10</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0000</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0001</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0010</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0011</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0100</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0101</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0110</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0111</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Base 2</strong></th>
<th style="text-align: center;"><strong>Base 10</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1000</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">1001</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1010</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">1011</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1100</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">1101</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1110</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">1111</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>En utilisant les nombres entiers signés:</p>
<ul>
<li>On peut écrire autant de nombres positifs que de négatifs.</li>
<li>Pour un nombre exprimé avec <span class="math inline">\(n\)</span> bits, les valeurs extrèmes sont <span class="math inline">\(\pm(2^{n-1}-1)\)</span></li>
</ul>
<div id="exm-valeurs-extremes-4-bits" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.4 </strong></span>Quelles sont les valeurs extrèmes pour des entiers signés représentés sur 4 bits?</p>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Inconvénients de la représentation signe et module
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Il y a deux zéros! Un <em>zéro</em> positif (0000 0000) et un <em>zéro</em> négatif (1000 0000).</li>
<li>Les opérations arithmétiques ne se font pas de la même manière qu’habituellement. Par exemple, sur 4 bits:
<ul>
<li><strong>Base 2</strong>: 0100 + 1011 = 1111</li>
<li><strong>Base 10</strong>: +4 + -3 = -7! (<strong>FAUX!</strong>)</li>
</ul></li>
</ul>
</div>
</div>
<div id="exm-representation-signe-module-8-bits" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.5 </strong></span>Écrivez la représentation signe et module sur 8 bits de:</p>
<ol type="a">
<li>15</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="representation_nombres_ordinateurs_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="a">
<li>-15</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="representation_nombres_ordinateurs_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="a">
<li>-10</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="representation_nombres_ordinateurs_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="a">
<li>Quel est l’intervalle de nombres entiers <em>signés</em> pouvant être représentés avec:
<ol type="i">
<li>8 bits?</li>
<li>16 bits?</li>
</ol></li>
</ol>
</div>
</section>
</section>
<section id="format-dun-nombre-en-virgule-flottante" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="format-dun-nombre-en-virgule-flottante"><span class="header-section-number">2.2</span> Format d’un nombre en virgule flottante</h2>
<p>La virgule flottante est une méthode d’écriture de nombres fréquemment utilisée dans les ordinateurs, équivalente à la notation scientifique en numération binaire.</p>
<p>Par exemple: <span class="math display">\[
+13,254 = \underbrace{+}_{\text{signe}} \underbrace{0,13254}_{\text{mantisse}} \times 10^{\overbrace{{2}}^{\text{exposant}}}
\]</span></p>
<section id="format-général" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="format-général">Format général</h3>
<p>Un nombre flottant est formé de trois éléments : la mantisse, l’exposant et le signe. Le bit de poids fort est le bit de signe : si ce bit est à 1, le nombre est négatif, et s’il est à 0, le nombre est positif. Les <span class="math inline">\(e\)</span> bits suivants représentent l’exposant biaisé (sauf valeur spéciale), et les <span class="math inline">\(m\)</span> bits suivants (<span class="math inline">\(m\)</span> bits de poids faible) représentent la mantisse.</p>
<div class="columns">
<div class="column" style="width:40%;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Signe</strong></th>
<th style="text-align: center;"><strong>Exposant biaisé</strong></th>
<th style="text-align: center;"><strong>Mantisse</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">(1 bit)</td>
<td style="text-align: center;">(e bits)</td>
<td style="text-align: center;">(m bits)</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/2/29/IEEE754_Format_General.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Format général de représentation des flottants</figcaption>
</figure>
</div>
</div>
</div>
<p>Nous reviendrons sur l’exposant biaisé à la section <a href="#sec-ieee754"><span>Section&nbsp;2.3</span></a>.</p>
</section>
<section id="opérations-sur-les-nombres-en-virgule-flottante" class="level3" data-number="2.2.1">
<h3 data-number="2.2.1" class="anchored" data-anchor-id="opérations-sur-les-nombres-en-virgule-flottante"><span class="header-section-number">2.2.1</span> Opérations sur les nombres en virgule flottante</h3>
<p>Pour simplifier la présentation et la compréhension, nous utiliserons la base décimale avec 7 chiffres de précision, tout comme le format <em>binary32</em> (format à simple précision), que nous verrons plus tard. Les principes fondamentaux sont les mêmes peu importe la base et le nombre de chiffres de précision. Nous utiliserons <span class="math inline">\(f\)</span> pour désigner la mantisse (en anglais on parle de <strong>float</strong>) et <span class="math inline">\(e\)</span> pour désigner l’exposant.</p>
<section id="additions-et-soustractions" class="level4" data-number="2.2.1.1">
<h4 data-number="2.2.1.1" class="anchored" data-anchor-id="additions-et-soustractions"><span class="header-section-number">2.2.1.1</span> Additions et soustractions</h4>
<p>Pour additionner (ou soustraire) des nombres en virgule flottante, nous devons les représenter avec le même exposant. La convention est de modifier l’exposant le <em>plus petit</em> pour le rendre égal à l’exposant le plus grand.</p>
<p><span class="math display">\[
\begin{array}{rrll}
&amp; e=5; &amp; s=1,234567 &amp; (123456,7) \\
+ &amp; e=2; &amp; s=1,017654 &amp; (101,7654) \\ \\
\hline
\\
&amp; e=5; &amp; s=1,234567 &amp;  \\
+ &amp; e=5; &amp; s=0,01017654 &amp; (\text{après déplacement de la virgule}) \\ \\
\hline
\\
&amp; e=5; &amp; s=1,235584654 &amp; (\text{somme réelle}: 123558,4654)
\end{array}
\]</span></p>
<p>Le résultat précédent correspond à la somme réelle des deux nombres. Le résultat sera ensuite arrondi à 7 chiffres et normalisé si nécessaire. Le résultat final est:</p>
<p><span class="math display">\[
\begin{array}{rrll}
&amp; e=5; &amp; s=1,235585 &amp; (\text{somme finale}: 123558,5)
\end{array}
\]</span></p>
<p>Les trois derniers chiffres du second nombre (654) sont essentiellement perdus. C’est ce que nous appelons l’erreur d’arrondi. Dans des cas extrèmes, la somme de deux nombres <em>différents de zéro</em> peut être égale à un de ces nombre.</p>
<div id="exm-addition-deux-nombres" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.6 </strong></span>Additionnez les deux nombres 123456,7 et 0,009876543, en utilisant 7 chiffres pour la mantisse.</p>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Attention
</div>
</div>
<div class="callout-body-container callout-body">
<p>Dans l’exemple précédent, il semblerait qu’un grand nombre de chiffres supplémentaires soit nécessaire pour s’assurer d’obtenir le bon résultat. En pratique, pour l’addition ou la soustraction en binaire, en utilisant une bonne implémentation, seulement un <em>guard bit</em>, un <em>rounding bit</em> et un <em>sticky bit</em> sont nécessaires pour obtenir un bon résultat.</p>
</div>
</div>
<p>Un autre problème peut se produire lorsque des approximations de deux nombres presque égaux sont soustraites.</p>
<div id="exm-soustraction-deux-nombres-presque-egaux" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.7 </strong></span>Effectuez la soustraction de 123457,1467 et 123456,659, en utilisant 7 chiffres pour la mantisse.</p>
</div>
<div id="exm-soustraction-deux-nombres-presque-egaux-erreur" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.8 </strong></span>Calculez l’erreur relative faite à l’<a href="#exm-soustraction-deux-nombres-presque-egaux">Exemple&nbsp;<span>2.7</span></a>.</p>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Attention
</div>
</div>
<div class="callout-body-container callout-body">
<p>L’<a href="https://www.wikiwand.com/en/Catastrophic_cancellation">annulation catastrophique</a> de l’<a href="#exm-soustraction-deux-nombres-presque-egaux">Exemple&nbsp;<span>2.7</span></a> illustre le danger de supposer que tous les chiffres d’un résultat sont pertinents.</p>
</div>
</div>
<div id="exm-difference-de-carres" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.9 </strong></span>Soit deux nombres <span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span>. La manière naïve de calculer la fonction <span class="math inline">\(x^2-y^2\)</span> en virgule flottante est sujette à l’annulation catastrophique, lorsque <span class="math inline">\(x\)</span> et <span class="math inline">\(y\)</span> sont proches. En effet, la soustraction peut faire apparaître les erreurs d’arrondi dans l’élévation au carré. La fonction factorisée <span class="math inline">\((x+y)(x-y)\)</span> évite l’annulation catastrophique car elle évite d’introduire des erreurs d’arrondis avant la soustraction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> <span class="dv">1</span><span class="op">+</span><span class="dv">2</span><span class="op">**</span>(<span class="op">-</span><span class="dv">29</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> <span class="dv">1</span><span class="op">+</span><span class="dv">2</span><span class="op">**</span>(<span class="op">-</span><span class="dv">30</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>ds1 <span class="op">=</span> x<span class="op">**</span><span class="dv">2</span><span class="op">-</span>y<span class="op">**</span><span class="dv">2</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>ds2 <span class="op">=</span> (x<span class="op">+</span>y)<span class="op">*</span>(x<span class="op">-</span>y)</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>err <span class="op">=</span> <span class="bu">abs</span>(ds1<span class="op">-</span>ds2)<span class="op">/</span>ds2</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(ds1, ds2, err)</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.862645149230957e-09 1.8626451518330422e-09 1.3969838599716539e-09</code></pre>
</div>
</div>
</div>
</section>
<section id="multiplications-et-divisions" class="level4" data-number="2.2.1.2">
<h4 data-number="2.2.1.2" class="anchored" data-anchor-id="multiplications-et-divisions"><span class="header-section-number">2.2.1.2</span> Multiplications et divisions</h4>
<p>Contrairement à l’addition et la soustraction, il n’y a pas de problème d’annulation catastrophique pour la multiplication ou la division.</p>
<p>Pour multiplier, les mantisses sont multipliées et les exposants sont additionnés. Le résultat est ensuite arrondi et normalisé. Pour diviser, les mantisses sont divisées et les exposants sont soustraits. Le résultat est ensuite arrondi et normalisé.</p>
<div id="exm-multiplication-virgule-flottante" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.10 </strong></span>Effectuez la multiplication de 4734,612 et 541724,2, en utilisant 7 chiffres pour la mantisse.</p>
</div>
</section>
</section>
</section>
<section id="sec-ieee754" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-ieee754"><span class="header-section-number">2.3</span> La norme IEEE754</h2>
<p>En informatique, l’IEEE 754 est une norme sur l’arithmétique à virgule flottante mise au point par le <em>Institute of Electrical and Electronics Engineers</em>. Elle est la norme la plus employée actuellement pour le calcul des nombres à virgule flottante avec les CPU et les FPU. La norme définit les formats de représentation des nombres à virgule flottante (signe, mantisse, exposant, nombres dénormalisés) et valeurs spéciales (infinis et NaN), en même temps qu’un ensemble d’opérations sur les nombres flottants. Il décrit aussi cinq modes d’arrondi et cinq exceptions (comprenant les conditions dans lesquelles une exception se produit, et ce qui se passe dans ce cas).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/2/29/IEEE754_Format_General.png" class="img-fluid figure-img"></p>
<figcaption class="figure-caption">Format général d’un nombre en virgule flottante.</figcaption>
</figure>
</div>
<section id="biais-de-lexposant" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="biais-de-lexposant">Biais de l’exposant</h3>
<p>L’exposant peut être positif ou négatif. Cependant, la représentation habituelle des nombres signés (complément à 2) rendrait la comparaison entre les nombres flottants un peu plus difficile. Pour régler ce problème, l’exposant est <strong>biaisé</strong>, afin de le stocker sous forme d’un nombre non signé. Le terme <strong>biaisé</strong> signifie que l’exposant est stocké sous forme d’entier positif, mais pour trouver l’exposant réel, il faut soustraire une valeur (le biais) à celle stockée.</p>
<p>Ce biais est de <span class="math inline">\(2^{e-1}-1\)</span> (<span class="math inline">\(e\)</span> représente le nombre de bits de l’exposant) ; il s’agit donc d’une valeur constante une fois que le nombre de bits <span class="math inline">\(e\)</span> est fixé.</p>
<p>Par exemple, dans le cas où l’exposant est composé de 8 bits, nous avons <span class="math inline">\(e=8\)</span> et le biais est de <span class="math inline">\(2^{8-1}-1=127\)</span>.</p>
<p>L’interprétation d’un nombre (autre qu’infini) est donc : <em>valeur</em> = <em>signe</em> x 2<sup>(<em>exposant</em>−<em>biais</em>)</sup> x <em>mantisse</em> avec:</p>
<ul>
<li><em>signe</em> = <span class="math inline">\(\pm\)</span> 1</li>
<li><em>biais</em> = <span class="math inline">\(2^{e-1}-1\)</span></li>
</ul>
</section>
<section id="exceptions" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="exceptions">Exceptions</h3>
<p>Le bit de poids fort de la mantisse est déterminé par la valeur de l’exposant biaisé. Si l’exposant biaisé est différent de 0 et de <span class="math inline">\(2^e-1\)</span>, le bit de poids fort de la mantisse est 1, et le nombre est dit <strong>normalisé</strong>. Si l’exposant biaisé est nul, le bit de poids fort de la mantisse est nul, et le nombre est <strong>dénormalisé</strong>.</p>
<p>Il y a trois cas particuliers:</p>
<ul>
<li>si l’exposant biaisé et la mantisse sont tous deux nuls, le nombre est <span class="math inline">\(\pm\)</span> 0 (selon le bit de signe)</li>
<li>si l’exposant biaisé est égal à <span class="math inline">\(2^e-1\)</span>, et si la mantisse est nulle, le nombre est <span class="math inline">\(\pm\)</span> infini (selon le bit de signe)</li>
<li>si l’exposant biaisé est égal à <span class="math inline">\(2^e-1\)</span>, mais que la mantisse n’est pas nulle, le nombre est <em>NaN</em> (not a number : pas un nombre).</li>
</ul>
<p>Un nombre flottant normalisé a une valeur <span class="math inline">\(v\)</span> donnée par la formule suivante: <span class="math display">\[
v = s \times 2^e \times (1+f)
\]</span></p>
<ul>
<li><span class="math inline">\(s=\pm 1\)</span> représente le signe (selon le bit de signe);</li>
<li><span class="math inline">\(e\)</span> est l’exposant avant son biais de <span class="math inline">\(2^{e-1}-1\)</span>;</li>
<li><span class="math inline">\(f\)</span> représente un nombre en binaire compris entre 0 et 1.</li>
</ul>
<p>Les nombres dénormalisés suivent le même principe, sauf qu’une seule valeur de <span class="math inline">\(e\)</span> est possible, <span class="math inline">\(e=2-2^{e-1}\)</span>. Nous avons donc <span class="math display">\[
v = s \times 2^e \times (0+f)
\]</span></p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Il y a deux zéros: +0 et -0 (zéro positif et zéro négatif), selon la valeur du bit de signe;</li>
<li>Il y a deux infinis: <span class="math inline">\(+\infty\)</span> et <span class="math inline">\(-\infty\)</span>, selon la valeur du bit de signe;</li>
<li>Les zéros et les nombres dénormalisés ont un exposant biaisé de 0; tous les bits du champ <em>exposant</em> sont donc à 0;</li>
<li>Les NaNs et les infinis ont un exposant biaisé de <span class="math inline">\(2^e-1\)</span>; tous les bits du champ <em>exposant</em> sont donc à 1;</li>
<li>Les NaNs peuvent avoir un signe et une partie significative mais ceux-ci n’ont aucun sens en tant que valeur réelle (sauf pour la signalisation, qui peut activer une exception, et la correction d’erreurs) ;</li>
</ul>
</div>
</div>
<p>La mantisse est représentée par: <span id="eq-mantisse-1-2"><span class="math display">\[
\begin{aligned}
f &amp;= \sum_{i=1}^{m} b_i 2^{-i}, \qquad b_i \in \{0, 1 \} \\
&amp;= b_1 2^{-1}+b_2 2^{-2}+\ldots + b_m 2^{-m}
\end{aligned}
\tag{2.1}\]</span></span> pour un entier fixé <span class="math inline">\(m\)</span>, la taille de la mantisse. L’équation (<a href="#eq-mantisse-1-2">Équation&nbsp;<span>2.1</span></a>) représente des nombres dans l’intervalle <span class="math inline">\([1,2[\)</span>. De manière équivalente, nous pouvons écrire <span id="eq-mantisse-0-puissance-2"><span class="math display">\[
\begin{aligned}
f &amp;= 2^{-m} \sum_{i=1}^{m} b_i 2^{m-i} = 2^{-m} z, \qquad b_i \in \{0, 1 \}
\end{aligned}
\tag{2.2}\]</span></span> pour un entier <span class="math inline">\(z\)</span> dans l’ensemble <span class="math inline">\(\{ 0, 1, \ldots, 2^m-1 \}\)</span>.</p>
<div id="exm-virgule-flottante-1-bit" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.11 </strong></span>Écrivez toutes les mantisses possibles si le nombre de bits de la mantisse est de 1, c’est-à-dire <span class="math inline">\(m=1\)</span>.</p>
</div>
<div id="exm-virgule-flottante-2-bits" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.12 </strong></span>Écrivez toutes les mantisses possibles si le nombre de bits de la mantisse est de 2, c’est-à-dire <span class="math inline">\(m=2\)</span>.</p>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>L’expression <span class="math inline">\(f = \sum_{i=1}^{m} b_i 2^{-i}\)</span> peut être calculée facilement lorsque tous les <span class="math inline">\(b_i=1\)</span>. Nous obtenons: <span class="math display">\[
f = \sum_{i=1}^{m} 1 \cdot 2^{-i} = 2-2^{-m}
\]</span></p>
</div>
</div>
<div id="def-epsilon-machine" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 2.3 (L’epsilon d’une machine) </strong></span>L’epsilon d’une machine est défini comme le plus petit nombre qui, ajouté à un, donne un résultat différent de un.</p>
<p>En utilisant l’équation (<a href="#eq-mantisse-0-puissance-2">Équation&nbsp;<span>2.2</span></a>), nous remarquons que le plus petit nombre (autre que 0) possible est <span class="math inline">\(2^{-m}\)</span>.</p>
<p>Pour déterminer l’epsilon de la machine en <code>Python</code>, on utilise la commande <code>sys.float_info.epsilon</code> du module <code>sys</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>sys.float_info.epsilon</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2.220446049250313e-16</code></pre>
</div>
</div>
</div>
<p>Nous pouvons aussi utiliser un petit programme pour déterminer l’epsilon de la machine.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>eps <span class="op">=</span> <span class="fl">1.0</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="cf">while</span> eps <span class="op">+</span> <span class="dv">1</span> <span class="op">&gt;</span> <span class="dv">1</span>:</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    eps <span class="op">/=</span> <span class="dv">2</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>eps <span class="op">*=</span> <span class="dv">2</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"L'epsilon machine est:"</span>, eps)</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>L'epsilon machine est: 2.220446049250313e-16</code></pre>
</div>
</div>
<p>En clair, si nous additionnons un nombre plus petit que l’epsilon machine, le résultat reste inchangé.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>eps <span class="op">=</span> sys.float_info.epsilon</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="dv">1</span><span class="op">+</span>eps, <span class="dv">1</span><span class="op">+</span>eps<span class="op">/</span><span class="dv">2</span>)</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>1.0000000000000002 1.0</code></pre>
</div>
</div>
</section>
<section id="le-format-à-virgule-flottante-à-précision-simple" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="le-format-à-virgule-flottante-à-précision-simple"><span class="header-section-number">2.3.1</span> Le format à virgule flottante à précision simple</h3>
<p>Le standard <a href="https://www.wikiwand.com/fr/IEEE%20754">IEEE 754</a> spécifie un format à précision simple comme:</p>
<ul>
<li>un signe : 1 bit</li>
<li>exposant biaisé : 8 bits</li>
<li>mantisse : 23 bits + 1 bit implicite</li>
</ul>
<p>L’exposant est un entier non signé de 8 bits de 0 à 255 sous la forme biaisée, c’est-à-dire que pour obtenir l’exposant réel, nous devons lui soustraire 127. Les exposants peuvent prendre les valeurs entières de -126 à +127 car les exposants -127 (seulement des zéros) et +128 (seulement des uns) sont réservés pour des nombres spéciaux.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="representation_nombres_ordinateurs_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La valeur est donc donnée par:</p>
<p><span class="math display">\[
(-1)^{b_{31}}\times 2^{(b_{30}b_{29}\ldots b_{23})_2-127}\times (1,b_{22}b_{21}\ldots b_0)_2
\]</span> ce qui donne <span class="math display">\[
\text{valeur}=(-1)^{\text{signe}}\times 2^{(E-127)}\times \left( 1+ \sum_{i=1}^{23} b_{23-i} 2^{-i}\right)
\]</span></p>
<p>Dans l’exemple précédent, nous avons:</p>
<ul>
<li>signe = <span class="math inline">\(b_{31}\)</span> = 0;</li>
<li><span class="math inline">\((-1)^{\text{signe}}=(-1)^0=+1\in \{-1,+1\}\)</span>;</li>
<li><span class="math inline">\(E=(b_{30}b_{29}\ldots b_{23})_2=\sum_{i=0}^7 b_{23+i}2^{+i}=124\in \{1,\ldots, (2^8-1)-1\}=\{1,\ldots, 254\}\)</span>;</li>
<li><span class="math inline">\(2^{(E-127)}=2^{124-127}=2^{-3}\in \{2^{-126},\ldots, 2^{127}\}\)</span>;</li>
<li><span class="math inline">\(1,b_{22}b_{21}\ldots b_0=1+\sum_{i=1}^{23} b_{23-i}2^{-i}=1+1\cdot 2^{-2}=1,25\in \{1,1+2^{-23},\ldots, 2-2^{-23}\} \subset [1;2-2^{-23}] \subset [1;2[\)</span></li>
</ul>
<section id="lencodage-de-lexposant" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="lencodage-de-lexposant">L’encodage de l’exposant</h4>
<p>L’exposant du format à virgule flottante à précision simple est encodé de manière biaisée, avec un biais de 127 (<span class="math inline">\(2^{e-1}-1=2^{8-1}-1\)</span>).</p>
<ul>
<li>E<sub>min</sub>=01<sub>16</sub>-7F<sub>16</sub>=-126</li>
<li>E<sub>max</sub>=FE<sub>16</sub>-7F<sub>16</sub>=127</li>
<li>Biais de l’exposant = 7F<sub>16</sub>=127</li>
</ul>
<p>Pour obtenir l’exposant véritable, on doit soustraire 127 à l’exposant stocké.</p>
<p>Les exposants 00<sub>16</sub> et FF<sub>16</sub> ont une interprétation spéciale.</p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 15%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Exposant</th>
<th>Fraction = 0</th>
<th>Fraction <span class="math inline">\(\neq\)</span> 0</th>
<th>Équation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>00<sub>16</sub></td>
<td><span class="math inline">\(\pm\)</span> zéro</td>
<td>nombre dénormalisé</td>
<td><span class="math inline">\((-1)^{\text{signe}}\times 2^{-126}\times 0,\text{fraction}\)</span></td>
</tr>
<tr class="even">
<td>01<sub>16</sub>,…,FE<sub>16</sub></td>
<td>valeur normale</td>
<td>valeur normale</td>
<td><span class="math inline">\((-1)^{\text{signe}}\times 2^{\text{exposant}-127}\times 1,\text{fraction}\)</span></td>
</tr>
<tr class="odd">
<td>FF<sub>16</sub></td>
<td><span class="math inline">\(\pm\)</span> infini</td>
<td>NaN</td>
<td></td>
</tr>
</tbody>
</table>
</section>
<section id="cas-particuliers-dans-le-format-virgule-flottante-à-précision-simple" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="cas-particuliers-dans-le-format-virgule-flottante-à-précision-simple">Cas particuliers dans le format virgule flottante à précision simple</h4>
<p>Pour les exemples suivants, trouvez la représentation sous forme binaire et hexadécimale.</p>
<div id="exm-plus-petit-nombre-denormalise" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.13 </strong></span>Trouvez le plus petit nombre dénormalisé positif.</p>
</div>
<div id="exm-plus-grand-nombre-denormalise" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.14 </strong></span>Trouvez le plus grand nombre dénormalisé positif.</p>
</div>
<div id="exm-plus-petit-nombre-normalise" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.15 </strong></span>Trouvez le plus petit nombre normalisé positif.</p>
</div>
<div id="exm-plus-grand-nombre-normalise" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.16 </strong></span>Trouvez le plus grand nombre normalisé positif.</p>
</div>
<div id="exm-plus-grand-nombre-plus-petit-un" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 2.17 </strong></span>Trouvez le plus grand nombre plus petit que un.</p>
</div>
</section>
</section>
<section id="le-format-à-virgule-flottante-à-précision-double" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="le-format-à-virgule-flottante-à-précision-double"><span class="header-section-number">2.3.2</span> Le format à virgule flottante à précision double</h3>
<p><a href="https://evanw.github.io/float-toy/">Float Toy</a></p>
<p><a href="https://introcs.cs.princeton.edu/java/91float/">Princeton Float</a></p>
<p><a href="https://hackingcpp.com/cpp/lang/fundamental_types.html">Cheatsheets for ieee 754 representation</a></p>
<p><a href="https://www.wikiwand.com/fr/IEEE%20754">IEEE754 Wiki Wand</a></p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./systeme_numeration_v2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Systèmes de numération positionnelle</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./logique.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Logique</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>