<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.269">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Mathématiques discrètes - 1&nbsp; Systèmes de numération positionnelle</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./logique.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Aucun résultat",
    "search-matching-documents-text": "documents identiques",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://hypothes.is/embed.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Systèmes de numération positionnelle</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Mathématiques discrètes</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/desautm/mathdiscretes" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="./Mathématiques-discrètes.pdf" title="Download PDF" class="sidebar-tool px-1"><i class="bi bi-file-pdf"></i></a>
    <a href="" title="Share" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-share"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
            <i class="bi bi-bi-twitter pe-1"></i>
          Twitter
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="https://www.facebook.com/sharer/sharer.php?u=|url|">
            <i class="bi bi-bi-facebook pe-1"></i>
          Facebook
          </a>
        </li>
    </ul>
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Préface</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./systeme_numeration.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Systèmes de numération positionnelle</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logique.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Logique</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ensembles.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Théorie des ensembles</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./fonctions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Fonctions</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./notation_grand_o.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Notation grand O</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./algorithmes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Introduction aux algorithmes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./theorie_nombres.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Théorie des nombres</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preuves.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Preuves et raisonnement mathématique</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./denombrement.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Dénombrement</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./graphes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Graphes</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./arbres.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Arbres</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">Références</a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table des matières</h2>
   
  <ul>
  <li><a href="#système-décimal" id="toc-système-décimal" class="nav-link active" data-scroll-target="#système-décimal"><span class="toc-section-number">1.1</span>  Système décimal</a></li>
  <li><a href="#système-binaire" id="toc-système-binaire" class="nav-link" data-scroll-target="#système-binaire"><span class="toc-section-number">1.2</span>  Système binaire</a></li>
  <li><a href="#système-hexadécimal" id="toc-système-hexadécimal" class="nav-link" data-scroll-target="#système-hexadécimal"><span class="toc-section-number">1.3</span>  Système hexadécimal</a></li>
  <li><a href="#division-entière" id="toc-division-entière" class="nav-link" data-scroll-target="#division-entière"><span class="toc-section-number">1.4</span>  Division entière</a></li>
  <li><a href="#conversions-de-la-base-10-vers-une-base-b" id="toc-conversions-de-la-base-10-vers-une-base-b" class="nav-link" data-scroll-target="#conversions-de-la-base-10-vers-une-base-b"><span class="toc-section-number">1.5</span>  Conversions de la base 10 vers une base <span class="math inline">\(b\)</span></a>
  <ul class="collapse">
  <li><a href="#conversions-vers-binaire" id="toc-conversions-vers-binaire" class="nav-link" data-scroll-target="#conversions-vers-binaire"><span class="toc-section-number">1.5.1</span>  Conversions vers binaire</a></li>
  <li><a href="#conversions-vers-hexadécimal" id="toc-conversions-vers-hexadécimal" class="nav-link" data-scroll-target="#conversions-vers-hexadécimal"><span class="toc-section-number">1.5.2</span>  Conversions vers hexadécimal</a></li>
  <li><a href="#conversions-binaire---hexadécimal" id="toc-conversions-binaire---hexadécimal" class="nav-link" data-scroll-target="#conversions-binaire---hexadécimal"><span class="toc-section-number">1.5.3</span>  Conversions binaire - hexadécimal</a></li>
  </ul></li>
  <li><a href="#applications-des-nombres-binaires-et-hexadécimaux" id="toc-applications-des-nombres-binaires-et-hexadécimaux" class="nav-link" data-scroll-target="#applications-des-nombres-binaires-et-hexadécimaux"><span class="toc-section-number">1.6</span>  Applications des nombres binaires et hexadécimaux</a>
  <ul class="collapse">
  <li><a href="#vocabulaire-des-nombres-binaires" id="toc-vocabulaire-des-nombres-binaires" class="nav-link" data-scroll-target="#vocabulaire-des-nombres-binaires"><span class="toc-section-number">1.6.1</span>  Vocabulaire des nombres binaires</a></li>
  <li><a href="#adresse-ip" id="toc-adresse-ip" class="nav-link" data-scroll-target="#adresse-ip"><span class="toc-section-number">1.6.2</span>  Adresse IP</a></li>
  <li><a href="#adresse-mac" id="toc-adresse-mac" class="nav-link" data-scroll-target="#adresse-mac"><span class="toc-section-number">1.6.3</span>  Adresse MAC</a></li>
  <li><a href="#couleurs" id="toc-couleurs" class="nav-link" data-scroll-target="#couleurs"><span class="toc-section-number">1.6.4</span>  Couleurs</a></li>
  </ul></li>
  <li><a href="#addition-en-binaire" id="toc-addition-en-binaire" class="nav-link" data-scroll-target="#addition-en-binaire"><span class="toc-section-number">1.7</span>  Addition en binaire</a>
  <ul class="collapse">
  <li><a href="#procédure-pour-laddition" id="toc-procédure-pour-laddition" class="nav-link" data-scroll-target="#procédure-pour-laddition">Procédure pour l’addition</a></li>
  </ul></li>
  <li><a href="#représentation-des-entiers" id="toc-représentation-des-entiers" class="nav-link" data-scroll-target="#représentation-des-entiers"><span class="toc-section-number">1.8</span>  Représentation des entiers</a>
  <ul class="collapse">
  <li><a href="#entiers-non-signés" id="toc-entiers-non-signés" class="nav-link" data-scroll-target="#entiers-non-signés"><span class="toc-section-number">1.8.1</span>  Entiers non signés</a></li>
  <li><a href="#entiers-signés" id="toc-entiers-signés" class="nav-link" data-scroll-target="#entiers-signés"><span class="toc-section-number">1.8.2</span>  Entiers signés</a></li>
  <li><a href="#complément-à-1" id="toc-complément-à-1" class="nav-link" data-scroll-target="#complément-à-1"><span class="toc-section-number">1.8.3</span>  Complément à 1</a></li>
  <li><a href="#complément-à-2" id="toc-complément-à-2" class="nav-link" data-scroll-target="#complément-à-2"><span class="toc-section-number">1.8.4</span>  Complément à 2</a></li>
  <li><a href="#addition-de-nombres-par-complémentation-à-deux" id="toc-addition-de-nombres-par-complémentation-à-deux" class="nav-link" data-scroll-target="#addition-de-nombres-par-complémentation-à-deux"><span class="toc-section-number">1.8.5</span>  Addition de nombres par complémentation à deux</a></li>
  <li><a href="#opérateurs-bit-à-bit" id="toc-opérateurs-bit-à-bit" class="nav-link" data-scroll-target="#opérateurs-bit-à-bit"><span class="toc-section-number">1.8.6</span>  Opérateurs bit à bit</a></li>
  <li><a href="#left-shift" id="toc-left-shift" class="nav-link" data-scroll-target="#left-shift"><span class="toc-section-number">1.8.7</span>  LEFT-SHIFT &lt;&lt;</a></li>
  <li><a href="#right-shift" id="toc-right-shift" class="nav-link" data-scroll-target="#right-shift"><span class="toc-section-number">1.8.8</span>  RIGHT-SHIFT &gt;&gt;</a></li>
  <li><a href="#complément-à-un-même-chose-que-not" id="toc-complément-à-un-même-chose-que-not" class="nav-link" data-scroll-target="#complément-à-un-même-chose-que-not"><span class="toc-section-number">1.8.9</span>  COMPLÉMENT À UN ~ (MÊME CHOSE QUE NOT)</a></li>
  </ul></li>
  <li><a href="#représentation-des-nombres-en-virgule-flottante" id="toc-représentation-des-nombres-en-virgule-flottante" class="nav-link" data-scroll-target="#représentation-des-nombres-en-virgule-flottante"><span class="toc-section-number">1.9</span>  Représentation des nombres en virgule flottante</a>
  <ul class="collapse">
  <li><a href="#la-norme-ieee754" id="toc-la-norme-ieee754" class="nav-link" data-scroll-target="#la-norme-ieee754"><span class="toc-section-number">1.9.1</span>  La norme IEEE754</a></li>
  </ul></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/desautm/mathdiscretes/edit/main/systeme_numeration.qmd" class="toc-action">Éditez cette page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content column-body" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Systèmes de numération positionnelle</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Un système de numération est un ensemble de règles qui permettent de représenter des nombres. Le plus ancien est probablement le système unaire où le symbole | représente l’entier un, || représente l’entier deux, ||| pour trois, |||| pour quatre et ainsi de suite. Ce système atteint vite ses limites, mais il permet de mettre en évidence le fait qu’il existe plusieurs façons de représenter les entiers.</p>
<table class="table">
<colgroup>
<col style="width: 20%">
<col style="width: 31%">
<col style="width: 23%">
<col style="width: 24%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Nom français</strong></th>
<th style="text-align: center;"><strong>Système unaire</strong></th>
<th style="text-align: center;"><strong>Système décimal</strong></th>
<th style="text-align: center;"><strong>Chiffres romains</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Zéro</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">Un</td>
<td style="text-align: center;">|</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">I</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Deux</td>
<td style="text-align: center;">||</td>
<td style="text-align: center;">2</td>
<td style="text-align: center;">II</td>
</tr>
<tr class="even">
<td style="text-align: center;">Trois</td>
<td style="text-align: center;">|||</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">III</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">Douze</td>
<td style="text-align: center;">|||| |||| ||||</td>
<td style="text-align: center;">12</td>
<td style="text-align: center;">XII</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
</tbody>
</table>
<p>Dans la table ci-dessus, on remarque que sur une ligne donnée, on retrouve quatre manières différentes de représenter le même entier. Pour le reste de cette section, il sera important de dissocier la <strong>représentation</strong> d’un nombre et sa <strong>valeur</strong>.</p>
<div id="def-systeme-numeration" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 1.1 (Système de numération) </strong></span>Un <strong>système de numération</strong> permet de compter des objets et de les représenter par des nombres. Un système de numération <strong>positionnel</strong> possède trois éléments:</p>
<ul>
<li>Base <span class="math inline">\(b\)</span> (un entier supérieur à 1)</li>
<li>Symboles (digits): 0, 1, 2, …, <span class="math inline">\(b\)</span>-1</li>
<li>Poids des symboles selon la position et la base, où poids=base<sup>position</sup></li>
</ul>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Lorsque plusieurs bases interviennent dans un même contexte, on écrit <span class="math inline">\((a_n \ldots a_1a_0)_b\)</span> pour indiquer que le nombre représenté en base <span class="math inline">\(b\)</span>.</p>
</div>
</div>
<div id="def-representation-polynomiale" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 1.2 (Représentation polynomiale) </strong></span>Le système positionnel utilise la <strong>représentation polynomiale</strong>. Celle-ci est donnée par: <span class="math display">\[
(a_na_{n-1}\ldots a_1a_0,a_{-1}a_{-2}\ldots a_{-m})_b = a_nb^n+a_{n-1}b^{n-1}+\ldots +a_1b^1+a_0b^0+a_{-1}b^{-1}+\ldots +a_{-m}b^{-m}
\]</span> où <span class="math inline">\(b\)</span> est la <strong>base</strong> et les <span class="math inline">\(a_i\)</span> sont des <strong>coefficients</strong> (les symboles de votre système de numération).</p>
</div>
<section id="système-décimal" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="système-décimal"><span class="header-section-number">1.1</span> Système décimal</h2>
<p>Il s’agit du système de numération le plus utilisé dans notre société. On peut le résumer avec les trois règles suivantes.</p>
<ul>
<li>Base = 10</li>
<li>Symboles ordonnés qu’on nomme les <em>chiffres</em> : 0, 1, 2, 3, 4, 5, 6, 7, 8, 9.</li>
<li>Le poids des symboles est donné par 10<sup>position</sup></li>
</ul>
<div id="exm-decimal-3482" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.1 </strong></span>Représentez le nombre 3482 sous une forme de numération positionnelle.</p>
<table class="table">
<colgroup>
<col style="width: 39%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Symboles (digits)</strong></th>
<th style="text-align: center;">3</th>
<th style="text-align: center;">4</th>
<th style="text-align: center;">8</th>
<th style="text-align: center;">2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Rang (position)</strong></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{V}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{V}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{V}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{V}\)</span></td>
</tr>
<tr class="even">
<td><strong>Poids</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td><strong>Valeur du poids</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td><strong>Valeur de chaque symbole (digits)</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Nous avons donc que 3482=</p>
</div>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Pour convertir un nombre de la base <span class="math inline">\(b\)</span> vers la base 10 (décimal), on trouve sa représentation polynomiale.</p>
</div>
</div>
<div id="exm-octal-vers-decimal" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.2 </strong></span>En utilisant la représentation polynomale en base 10, convertissez le nombre (176,21)<sub>8</sub>.</p>
</div>
</section>
<section id="système-binaire" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="système-binaire"><span class="header-section-number">1.2</span> Système binaire</h2>
<p>Ce concept est essentiel en informatique, puisque les processeurs des ordinateurs sont composés de transistors ne gérant que deux états chacun (0 ou 1). Un calcul informatique n’est donc qu’une suite d’opérations sur des paquets de 0 et de 1, appelés <strong>bits</strong>.</p>
<ul>
<li>Base = 2</li>
<li>Symboles ordonnés qu’on nomme les <em>bits</em>: 0, 1</li>
<li>Le poids des symboles est donné par 2<sup>position</sup></li>
</ul>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>En base 2, le <em>chiffre</em> 2 n’existe pas (c’est un <strong>nombre</strong>); tout comme le <em>chiffre</em> 10 n’existe pas en base 10 (c’est un <strong>nombre</strong>).</p>
</div>
</div>
<div id="exm-11001-en-decimal" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.3 </strong></span>Convertissez le nombre (11001)<sub>2</sub> en décimal.</p>
<table class="table">
<colgroup>
<col style="width: 34%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Symboles (digits)</strong></th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">1</th>
<th style="text-align: center;">0</th>
<th style="text-align: center;">0</th>
<th style="text-align: center;">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Rang (position)</strong></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{V}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{V}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{V}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{V}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{V}\)</span></td>
</tr>
<tr class="even">
<td><strong>Poids</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td><strong>Valeur du poids</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td><strong>Valeur de chaque symbole (digits)</strong></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
<p>Nous avons donc que (11001)<sub>2</sub> =</p>
</div>
<div id="exm-binaire-to-decimal" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.4 </strong></span>Convertissez les nombres suivants en base 10 (décimal).</p>
<ol type="a">
<li>(110)<sub>2</sub> =</li>
<li>(101101)<sub>2</sub> =</li>
<li>(0,1011)<sub>2</sub> =</li>
<li>(110,101)<sub>2</sub> =</li>
</ol>
</div>
<div id="exm-nombres-succedent-0-base-2-1" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.5 </strong></span>Quels sont les nombres qui, dans la base deux, succèdent à (0)<sub>2</sub>?</p>
</div>
<div id="exm-nombres-succedent-0-base-2-2" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.6 </strong></span>Quels sont les nombres qui, dans la base deux, succèdent à (1110)<sub>2</sub>?</p>
</div>
</section>
<section id="système-hexadécimal" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="système-hexadécimal"><span class="header-section-number">1.3</span> Système hexadécimal</h2>
<p>Le système hexadécimal est utilisé notamment en électronique numérique et en informatique car il est particulièrement commode et permet un compromis entre le code binaire des machines et une base de numération pratique à utiliser pour les ingénieurs. En effet, chaque chiffre hexadécimal correspond exactement à quatre chiffres binaires (ou bits), rendant les conversions très simples et fournissant une écriture plus compacte. L’hexadécimal a été utilisé la première fois en 1956 par les ingénieurs de l’ordinateur Bendix G-15.</p>
<ul>
<li>Base = 16</li>
<li>Symboles ordonnés qu’on nomme les <em>chiffres</em>: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, A, B, C, D, E, F</li>
<li>Le poids des symboles est donné par 16<sup>position</sup></li>
</ul>
<p>On remarque qu’en base 16, les dix chiffres de 0 à 9 ne suffisent pas. Il faut donc se doter de 6 symboles additionnels. On utilise les lettres de A à F avec la signification suivante:</p>
<p><span class="math display">\[
(A)_{16}=(10)_{10}, \quad (B)_{16}=(11)_{10}, \quad (C)_{16}=(12)_{10}, \quad (D)_{16}=(13)_{10}, \quad (E)_{16}=(14)_{10}, \quad (F)_{16}=(15)_{10}
\]</span></p>
<div id="exm-conversion-hexa-decimal" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.7 </strong></span>Trouvez la représentation en base 10 de:</p>
<ol type="a">
<li>(AB0)<sub>16</sub></li>
<li>(214,EA)<sub>16</sub></li>
</ol>
</div>
<div id="exm-nombres-succedent-hexa" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.8 </strong></span>Donnez, en base 16, les dix nombres qui succèdent à (AAA)<sub>16</sub>.</p>
</div>
</section>
<section id="division-entière" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="division-entière"><span class="header-section-number">1.4</span> Division entière</h2>
<div id="def-divisibilite" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 1.3 (Divisibilité) </strong></span>Si <span class="math inline">\(a\in\mathbb{Z}\)</span>, <span class="math inline">\(b\in\mathbb{Z}\)</span> et <span class="math inline">\(a\neq 0\)</span>, on dit que <span class="math inline">\(a\)</span> <strong>divise</strong> <span class="math inline">\(b\)</span> s’il existe un entier <span class="math inline">\(c\)</span> tel que <span class="math inline">\(b=ac\)</span>. L’entier <span class="math inline">\(a\)</span> est alors appelé <strong>facteur</strong> de <span class="math inline">\(b\)</span>.</p>
<p>Si <span class="math inline">\(a\)</span> <strong>divise</strong> <span class="math inline">\(b\)</span>, nous le notons <span class="math inline">\(a \mid b\)</span>.</p>
</div>
<div id="thm-divisibilite" class="theorem">
<p><span class="theorem-title"><strong>Théorème 1.1 (Divisibilité) </strong></span>Soit <span class="math inline">\(a\)</span>, <span class="math inline">\(b\)</span> et <span class="math inline">\(c\)</span> des nombres entiers quelconques, avec <span class="math inline">\(a\neq 0\)</span>.</p>
<ol type="1">
<li>Si <span class="math inline">\(a\mid b\)</span> et <span class="math inline">\(a\mid c\)</span> alors <span class="math inline">\(a\mid(b+c)\)</span> et <span class="math inline">\(a\mid (b-c)\)</span>.</li>
<li>Si <span class="math inline">\(a\mid b\)</span> alors <span class="math inline">\(a\mid (bc)\)</span>.</li>
<li>Si <span class="math inline">\(a\mid b\)</span> et <span class="math inline">\(b\mid c\)</span> alors <span class="math inline">\(a\mid c\)</span>.</li>
</ol>
</div>
<div id="exm-vrai-faux-divisibilite" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.9 </strong></span>Vrai ou faux? Justifiez en invoquant une définition, un théorème, en donnant une preuve ou un contre-exemple.</p>
<ol type="a">
<li><span class="math inline">\(7\mid 10\)</span></li>
<li><span class="math inline">\(-5\mid 10\)</span></li>
<li><span class="math inline">\(100\mid 10\)</span></li>
<li><span class="math inline">\(5\mid -10\)</span></li>
</ol>
</div>
<div id="thm-une-seule-paire-entiers" class="theorem">
<p><span class="theorem-title"><strong>Théorème 1.2 </strong></span>Soit <span class="math inline">\(a\)</span> et <span class="math inline">\(d\)</span> des entiers, avec <span class="math inline">\(d&gt;0\)</span>. Il existe une seule paire d’entiers <span class="math inline">\(q\)</span> et <span class="math inline">\(r\)</span> satisfaisant <span class="math display">\[
0\leq r&lt;d \quad \text{et} \quad a=dq+r
\]</span></p>
</div>
<div id="def-diviseur-dividende-quotient-reste" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 1.4 (Diviseur, dividende, quotient, reste) </strong></span>Considérons <span class="math inline">\(a\)</span> et <span class="math inline">\(d\)</span> des entiers, avec <span class="math inline">\(d&gt;0\)</span>. Le <a href="#thm-une-seule-paire-entiers">Théorème&nbsp;<span>1.2</span></a> stipule qu’il existe une seule paire d’entiers <span class="math inline">\(q\)</span> et <span class="math inline">\(r\)</span> satisfaisant <span class="math display">\[
a=dq+r \quad \text{et} \quad 0\leq r&lt;d
\]</span></p>
<p>Par exemple, si <span class="math inline">\(a=17\)</span> et <span class="math inline">\(d=3\)</span>, on a <span class="math display">\[
17=3\cdot 5+2 \quad \text{et} \quad 0\leq 2&lt;3
\]</span></p>
<ul>
<li>L’entier <span class="math inline">\(d=3\)</span> est appelé <strong>diviseur</strong>.</li>
<li>L’entier <span class="math inline">\(a=17\)</span> est appelé le <strong>dividende</strong>.</li>
<li>L’entier <span class="math inline">\(q=5\)</span> est appeléle <strong>quotient</strong> (notation: <span class="math inline">\(q=a\mathbf{div} d\)</span>).</li>
<li>L’entier <span class="math inline">\(r=2\)</span> est appelé le <strong>reste</strong>.</li>
</ul>
</div>
</section>
<section id="conversions-de-la-base-10-vers-une-base-b" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="conversions-de-la-base-10-vers-une-base-b"><span class="header-section-number">1.5</span> Conversions de la base 10 vers une base <span class="math inline">\(b\)</span></h2>
<p>Pour convertir un nombre entier de la base 10 vers une base <span class="math inline">\(b\)</span>, il faut effectuer de façon successive des divisions en utilisant la <a href="#def-diviseur-dividende-quotient-reste">Définition&nbsp;<span>1.4</span></a>. Les restes des divisions successives correspondent aux coefficients de la représentation polynomiale (<strong>lire de base en haut</strong>).</p>
<section id="conversions-vers-binaire" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="conversions-vers-binaire"><span class="header-section-number">1.5.1</span> Conversions vers binaire</h3>
<div id="exm-conversion-vers-binaire" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.10 </strong></span>Convertissez les nombres suivants en binaire.</p>
<ol type="a">
<li>115</li>
<li>71</li>
</ol>
</div>
<p>Nous pouvons utiliser la command <code>bin</code> de <code>Python</code> pour convertir des <strong>entiers</strong> décimaux en binaire.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">bin</span>(<span class="dv">115</span>))</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0b1110011</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">bin</span>(<span class="dv">71</span>))</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0b1000111</code></pre>
</div>
</div>
<p>Pour convertir un nombre fractionnaire en binaire, il suffit de multiplier (plutôt que de diviser) la partie fractionnaire en notant les parties entières et fractionnaires obtenues. Il faut ensuite répéter ces étapes avec la nouvelle partie fractionnaire et poursuivre le processus jusqu’à ce que la partie fractionnaire soit nulle. Les parties entières des résultats de ces produits correspondent aux coefficients de la représentation polynomiale (<strong>lire de haut en bas</strong>).</p>
<div id="exm-conversion-fractionnaire-binaire" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.11 </strong></span>Convertissez les nombres suivants en binaire.</p>
<ol type="a">
<li>(0,8125)<sub>10</sub></li>
<li>(0,15)<sub>10</sub></li>
</ol>
</div>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>La conversion en binaire ou en n’importe quelle base ne donne pas toujours une suite finie. Si c’est un nombre rationnel, la conversion donnera toujours une suite finie ou périodique.</p>
</div>
</div>
<div id="exm-conversion-binaire-totale" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.12 </strong></span>Convertissez en binaire les nombres suivants, en ne conservant que 6 chiffres pour la partie fractionnaire, au besoin.</p>
<ol type="a">
<li>(51,375)<sub>10</sub></li>
<li>(564,32)<sub>10</sub></li>
</ol>
</div>
</section>
<section id="conversions-vers-hexadécimal" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="conversions-vers-hexadécimal"><span class="header-section-number">1.5.2</span> Conversions vers hexadécimal</h3>
<div id="exm-conversion-decimal-hexadecimal" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.13 </strong></span>Convertissez les nombres décimaux suivants en hexadécimal.</p>
<ol type="a">
<li>(176,47)<sub>10</sub></li>
<li>(69,28)<sub>10</sub></li>
</ol>
</div>
<p>Nous pouvons utiliser la command <code>hex</code> de <code>Python</code> pour convertir des <strong>entiers</strong> décimaux en hexadécimal.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">hex</span>(<span class="dv">115</span>))</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0x73</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">hex</span>(<span class="dv">71</span>))</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0x47</code></pre>
</div>
</div>
</section>
<section id="conversions-binaire---hexadécimal" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="conversions-binaire---hexadécimal"><span class="header-section-number">1.5.3</span> Conversions binaire - hexadécimal</h3>
<p>Une des raisons pour lesquelles le format hexadécimal a été inventé est qu’il est particulièrement simple de convertir un nombre binaire en nombre hexadécimal et inversement.</p>
<table class="table">
<thead>
<tr class="header">
<th><strong>Hexa</strong></th>
<th>0</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Binaire</strong></td>
<td>0000</td>
<td>0001</td>
<td>0010</td>
<td>0011</td>
<td>0100</td>
<td>0101</td>
<td>0110</td>
<td>0111</td>
</tr>
<tr class="even">
<td><strong>Hexa</strong></td>
<td>8</td>
<td>9</td>
<td>A</td>
<td>B</td>
<td>C</td>
<td>D</td>
<td>E</td>
<td>F</td>
</tr>
<tr class="odd">
<td><strong>Binaire</strong></td>
<td>1000</td>
<td>1001</td>
<td>1010</td>
<td>1011</td>
<td>1100</td>
<td>1101</td>
<td>1110</td>
<td>1111</td>
</tr>
</tbody>
</table>
<p>Pour convertir un nombre binaire, on regroupe par <em>paquets</em> de 4 chiffres à partir de la virgule (pour la partie entière et la partie fractionnaire).</p>
<div id="exm-conversion-binaire-hexadecimal" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.14 </strong></span>Convertissez les nombres binaires suivants en hexadécimal.</p>
<ol type="a">
<li>(111001,1101)<sub>2</sub></li>
<li><span class="math inline">\((1110001,11\overline{001})_2\)</span></li>
</ol>
</div>
<div id="exm-conversion-hexadecimal-binaire" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.15 </strong></span>Convertissez les nombres hexadécimaux suivants en binaire.</p>
<ol type="a">
<li>(537,14)<sub>16</sub></li>
<li><span class="math inline">\((45B,1\overline{DE})_{16}\)</span></li>
</ol>
</div>
</section>
</section>
<section id="applications-des-nombres-binaires-et-hexadécimaux" class="level2" data-number="1.6">
<h2 data-number="1.6" class="anchored" data-anchor-id="applications-des-nombres-binaires-et-hexadécimaux"><span class="header-section-number">1.6</span> Applications des nombres binaires et hexadécimaux</h2>
<section id="vocabulaire-des-nombres-binaires" class="level3" data-number="1.6.1">
<h3 data-number="1.6.1" class="anchored" data-anchor-id="vocabulaire-des-nombres-binaires"><span class="header-section-number">1.6.1</span> Vocabulaire des nombres binaires</h3>
<p>Les codes binaires sont incontournables en informatique, car l’information la plus élémentaire est le <strong>bit</strong> (<em>binary-digit</em>).</p>
<dl>
<dt><strong>Quartet</strong></dt>
<dd>
Nombre binaire composé de 4 éléments binaires.
</dd>
<dt><strong>Octet</strong> (<em>byte</em>)</dt>
<dd>
Nombre binaire composé de 8 éléments binaires.
</dd>
<dt><strong>Mot</strong></dt>
<dd>
Nombre binaire composé de 16, 32 ou 64 éléments binaires.
</dd>
<dt><strong>LSB</strong> (Least Significant Bit)</dt>
<dd>
Bit le moins significatif ou bit de poids faible (élément le plus à droite).
</dd>
<dt><strong>MSB</strong> (Most Significant Bit)</dt>
<dd>
Bit le plus significatif ou bit de poids fort (élément le plus à gauche).
</dd>
</dl>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Truc
</div>
</div>
<div class="callout-body-container callout-body">
<p>Les mots de 8 ou de 16 bits écrits en binaire sont plus lisibles si on les inscrit en laissant un espace entre les groupes de quatre bits comme ceci: 0100 0001</p>
</div>
</div>
<div class="callout-tip callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Truc
</div>
</div>
<div class="callout-body-container callout-body">
<p>On a avantage à représenter les zéros non significatifs pour montrer la taille des codes transcrits. remarquez que ces 0 à gauche ne sont d’ailleurs pas toujours <em>non significatifs</em>. En effet, les codes binaires ne représentent pas toujours des valurs numériques. Ce sont parfois simplement des codes qui ne représentent pas des quantités. Inutile donc de faire de l’arithmétique avec ces codes. Dans ce cas, cela n’a aucun sens de vouloir les convertir en décimal et ce serait une erreur d’omettre l’écriture des zéros à gauche.</p>
</div>
</div>
</section>
<section id="adresse-ip" class="level3" data-number="1.6.2">
<h3 data-number="1.6.2" class="anchored" data-anchor-id="adresse-ip"><span class="header-section-number">1.6.2</span> Adresse IP</h3>
<p>Une adresse IP (Internet Protocol) est un numéro d’identification qui est attribué de façon permanente ou provisoire à chaque périphérique relié à un réseau informatique qui utilise l’Internet Protocol. L’adresse IP est à la base du système d’acheminement (le routage) des paquets de données sur Internet.</p>
<p>Il existe des adresses IP de version 4 sur 32 bits, et de version 6 sur 128 bits. La version 4 est actuellement la plus utilisée : elle est généralement représentée en notation décimale avec quatre nombres compris entre 0 et 255, séparés par des points, ce qui donne par exemple « 181.174.87.53 ».</p>
<div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/3/34/Adresse_Ipv4.svg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Adresse Ipv4</figcaption><p></p>
</figure>
</div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/4/4d/Ipv6_address-fr.svg" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Adresse Ipv6</figcaption><p></p>
</figure>
</div>
</div>
</section>
<section id="adresse-mac" class="level3" data-number="1.6.3">
<h3 data-number="1.6.3" class="anchored" data-anchor-id="adresse-mac"><span class="header-section-number">1.6.3</span> Adresse MAC</h3>
<p>Une adresse MAC (de l’anglais Media Access Control), parfois nommée adresse physique, est un identifiant physique stocké dans une carte réseau ou une interface réseau similaire. À moins qu’elle n’ait été modifiée par l’utilisateur, elle est unique au monde. Le MAC (acronyme de Media Access Control) n’a aucun rapport avec le Mac d’Apple (diminutif de Macintosh). Toutes les cartes réseau ont une adresse MAC, même celles contenues dans les PC et autres appareils connectés (tablette tactile, smartphone, consoles de jeux, réfrigérateurs, montres …).</p>
<p>On peut utiliser <code>Python</code> et le module <code>uuid</code> pour trouver l’adresse MAC de l’appareil que j’utilise pour écrire ces lignes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> uuid</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="bu">hex</span>(uuid.getnode()))</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>0xc0b5d7b3d9a2</code></pre>
</div>
</div>
</section>
<section id="couleurs" class="level3" data-number="1.6.4">
<h3 data-number="1.6.4" class="anchored" data-anchor-id="couleurs"><span class="header-section-number">1.6.4</span> Couleurs</h3>
<p>Rouge, vert, bleu, de l’acronyme RVB ou en anglais RGB « red, green, blue ») désigne un système de traitement optique, d’affichage électronique ou d’un codage de signal vidéo analogique, ou un codage informatique des couleurs.</p>
<p>Ce principe est exploité par un téléviseur, un écran vidéo ou d’ordinateur, lequel reproduit la couleur par synthèse additive, à partir de trois couleurs primaires : rouge, vert et bleu.</p>
<p>Pour l’univers infographique, la valeur de chacune des couleurs primaires s’exprime dans un intervalle entre 0 et le maximum, qui est soit 1 ou 100 %, soit 255.</p>
<p>L’informatique utilise des nombres codés en système binaire, par groupes de huit (octet). En attribuant un octet à chacun des canaux de couleur primaire, on obtient un nombre de couleurs tel que deux codes consécutifs, pour une ou plusieurs composantes, ne peuvent pas se distinguer sur un écran correctement réglé.</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 8%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Valeur</strong></th>
<th><strong>Couleur</strong></th>
<th><strong>Valeur</strong></th>
<th><strong>Couleur</strong></th>
<th><strong>Valeur</strong></th>
<th><strong>Couleur</strong></th>
<th><strong>Valeur</strong></th>
<th><strong>Couleur</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>#00FFFF</td>
<td>aqua / cyan</td>
<td>#008000</td>
<td>green (vert)</td>
<td>#000080</td>
<td>navy (bleu marine)</td>
<td>#C0C0C0</td>
<td>silver (argent)</td>
</tr>
<tr class="even">
<td>#000000</td>
<td>black (noir)</td>
<td>#808080</td>
<td>gray (gris)</td>
<td>#808000</td>
<td>olive (jaune olive)</td>
<td>#008080</td>
<td>teal (sarcelle)</td>
</tr>
<tr class="odd">
<td>#0000FF</td>
<td>blue (bleu)</td>
<td>#00FF00</td>
<td>lime (vert citron)</td>
<td>#800080</td>
<td>purple (violet)</td>
<td>#FFFFFF</td>
<td>white (blanc)</td>
</tr>
<tr class="even">
<td>#FF00FF</td>
<td>fuchsia / magenta (fuchsia)</td>
<td>#800000</td>
<td>maroon (bordeaux)</td>
<td>#FF0000</td>
<td>red (rouge)</td>
<td>#FFFF00</td>
<td>yellow (jaune)</td>
</tr>
</tbody>
</table>
<table class="table">
<colgroup>
<col style="width: 26%">
<col style="width: 19%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Couleur</strong></th>
<th style="text-align: center;"><strong>Valeur Rouge</strong></th>
<th style="text-align: center;"><strong>Valeur Vert</strong></th>
<th style="text-align: center;"><strong>Valeur Bleu</strong></th>
<th style="text-align: center;"><strong>Hexadécimal</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Red (rouge)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">#FF0000</td>
</tr>
<tr class="even">
<td style="text-align: center;">Green (vert)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">#00FF00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Blue (bleu)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">#0000FF</td>
</tr>
<tr class="even">
<td style="text-align: center;">Yellow (jaune)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">#FFFF00</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Orange</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">165 (A5)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">#FFA500</td>
</tr>
<tr class="even">
<td style="text-align: center;">Aqua</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">#00FFFF</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Navy blue (bleu marine)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">128 (80)</td>
<td style="text-align: center;">#000080</td>
</tr>
<tr class="even">
<td style="text-align: center;">Black (noir)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">0 (00)</td>
<td style="text-align: center;">#000000</td>
</tr>
<tr class="odd">
<td style="text-align: center;">White (blanc)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">255 (FF)</td>
<td style="text-align: center;">#FFFFFF</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="addition-en-binaire" class="level2" data-number="1.7">
<h2 data-number="1.7" class="anchored" data-anchor-id="addition-en-binaire"><span class="header-section-number">1.7</span> Addition en binaire</h2>
<p>La méthode pour l’addition en base 10 peut s’appliquer pour n’importe quelle base (principe de report). Pour additionner en binaire, on procède comme en décimal. Quand le résultat de la somme d’une colonne est supérieur à 1 (utilise plus de 1 <strong>bit</strong>), on reporte ce bit au voisin de gauche.</p>
<p>En binaire:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">+</th>
<th style="text-align: center;">0</th>
<th style="text-align: center;">1</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: center;">10</td>
</tr>
</tbody>
</table>
<section id="procédure-pour-laddition" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="procédure-pour-laddition">Procédure pour l’addition</h3>
<ol type="1">
<li>Superposer les nombres en colonnes de telle sorte que les chiffres de même position soit alignés verticalement.</li>
<li>Additionner colonne par colonne, à partir de la droite, en effectuant les reports appropriés.</li>
</ol>
<div id="exm-addition-binaire" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.16 </strong></span>Effectuez les additions demandées:</p>
<ol type="a">
<li>(1011)<sub>2</sub>+(1001)<sub>2</sub></li>
<li>(1011,011)<sub>2</sub>+(110,01)<sub>2</sub></li>
<li>(110111,011)<sub>2</sub>+(10101,0101)<sub>2</sub></li>
</ol>
</div>
</section>
</section>
<section id="représentation-des-entiers" class="level2" data-number="1.8">
<h2 data-number="1.8" class="anchored" data-anchor-id="représentation-des-entiers"><span class="header-section-number">1.8</span> Représentation des entiers</h2>
<p>Il existe de nombreuses manières de représenter un nombre entier dans la mémoir d’un ordinateur. Nous n’en verrons que quelques unes.</p>
<section id="entiers-non-signés" class="level3" data-number="1.8.1">
<h3 data-number="1.8.1" class="anchored" data-anchor-id="entiers-non-signés"><span class="header-section-number">1.8.1</span> Entiers non signés</h3>
<div id="def-entiers-non-signes" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 1.5 (Entiers non signés (nombres positifs)) </strong></span>Un nombre <strong>entier non signé</strong> (positif) est représenté par un nombre de bits préalablement fixé. Au besoin, on complète le nombre par des zéros à gauche fin d’avoir le nombre total de bits choisi.</p>
</div>
<div id="exm-entiers-non-signes" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.17 </strong></span>Transformez les entiers décimaux suivants en entiers non signés sur un octet (huit bits).</p>
<ol type="a">
<li>143</li>
<li>15</li>
<li>30</li>
</ol>
</div>
<div id="exm-plus-grand-entier-non-signe" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.18 </strong></span>Quel est le plus grand entier non signé pouvant être représenté avec:</p>
<ol type="a">
<li>8 bits?</li>
<li>32 bits?</li>
<li><span class="math inline">\(n\)</span> bits?</li>
</ol>
</div>
</section>
<section id="entiers-signés" class="level3" data-number="1.8.2">
<h3 data-number="1.8.2" class="anchored" data-anchor-id="entiers-signés"><span class="header-section-number">1.8.2</span> Entiers signés</h3>
<p>Pour travailler avec des entiers qui peuvent être positifs ou négatifs, il faut inclure le signe du nombre dans sa représentation, et l’on parle alors d’entiers signés.</p>
<div id="def-entiers-signes" class="theorem definition">
<p><span class="theorem-title"><strong>Définition 1.6 (Entiers signés (représentation signe et module)) </strong></span>Un nombre <strong>entier signé</strong> (généralement représenté dans un octet) est un nombre où le 1<sup>er</sup> bit (à gauche) est réservé au signe, et les autres bits permettent d’indiquer la valeur absolue du nombre. Pour indique qu’un nombre est positif (+), le 1<sup>er</sup> bit est <code>0</code>, et pour un nombre négatif (-), le 1<sup>er</sup> bit est <code>1</code>.</p>
</div>
<div id="exm-completion-tableau-signe-module-4-bits" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.19 </strong></span>Complétez les tableaux suivants qui indiquent la représentation signe et module sur 4 bits.</p>
<div class="columns">
<div class="column" style="width:40%;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Base 2</strong></th>
<th style="text-align: center;"><strong>Base 10</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0000</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0001</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0010</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0011</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0100</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0101</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">0110</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">0111</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:10%;">

</div><div class="column" style="width:40%;">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Base 2</strong></th>
<th style="text-align: center;"><strong>Base 10</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">1000</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">1001</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1010</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">1011</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1100</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">1101</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">1110</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">1111</td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>En utilisant les nombres entiers signés:</p>
<ul>
<li>On peut écrire autant de nombres positifs que de négatifs.</li>
<li>Pour un nombre exprimé avec <span class="math inline">\(n\)</span> bits, les valeurs extrèmes sont <span class="math inline">\(\pm(2^{n-1}-1)\)</span></li>
</ul>
<div id="exm-valeurs-extremes-4-bits" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.20 </strong></span>Quelles sont les valeurs extrèmes pour des entiers signés représentés sur 4 bits?</p>
</div>
<div class="callout-warning callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Inconvénients de la représentation signe et module
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Il y a deux zéros! Un <em>zéro</em> positif (0000 0000) et un <em>zéro</em> négatif (1000 0000).</li>
<li>Les opérations arithmétiques ne se font pas de la même manière qu’habituellement. Par exemple, sur 4 bits:
<ul>
<li><strong>Base 2</strong>: 0100 + 1011 = 1111</li>
<li><strong>Base 10</strong>: +4 + -3 = -7! (<strong>FAUX!</strong>)</li>
</ul></li>
</ul>
</div>
</div>
<div id="exm-representation-signe-module-8-bits" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.21 </strong></span>Écrivez la représentation signe et module sur 8 bits de:</p>
<ol type="a">
<li>15</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="systeme_numeration_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="a">
<li>-15</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="systeme_numeration_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="a">
<li>-10</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<p><img src="systeme_numeration_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ol type="a">
<li>Quel est l’intervalle de nombres entiers <em>signés</em> pouvant être représentés avec:
<ol type="i">
<li>8 bits?</li>
<li>16 bits?</li>
</ol></li>
</ol>
</div>
</section>
<section id="complément-à-1" class="level3" data-number="1.8.3">
<h3 data-number="1.8.3" class="anchored" data-anchor-id="complément-à-1"><span class="header-section-number">1.8.3</span> Complément à 1</h3>
<p>Le complément à un d’un nombre binaire est la valeur obtenue en inversant tous les bits de ce nombre (en permutant les 0 par des 1 et inversement). Le complément à un d’un nombre se comporte alors comme le négatif du nombre original dans certaines opérations arithmétiques.</p>
<p>D’un point de vue algébrique, qui est plus général, c’est l’opération qui consiste à complémenter un nombre écrit en base <span class="math inline">\(b\)</span> sur <span class="math inline">\(n\)</span> chiffres à <span class="math inline">\(b^n-1\)</span>. C’est-à-dire que le complément d’un nombre <span class="math inline">\(a\)</span> s’obtient par <span class="math inline">\((b^n−1)−a\)</span>.</p>
<div id="exm-complement-a-un" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.22 </strong></span>Le complément à 1 de 0100 =</p>
</div>
<div class="callout-note callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Remarquons que dans l’<a href="#exm-complement-a-un">Exemple&nbsp;<span>1.22</span></a>, le complément à un représente le calcul de <span class="math inline">\((2^4-1)-0100=1111-0100=1011\)</span></p>
</div>
</div>
<div id="exm-complement-a-un-4-bits" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.23 </strong></span>Représentez dans le tableau suivant toutes les valeurs possibles du complément à un sur 4 bits.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><strong>Décimal</strong></th>
<th style="text-align: center;"><strong>+</strong></th>
<th style="text-align: center;"><strong>-</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;"><span class="math inline">\(\phantom{000}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\phantom{000}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">4</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">5</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: center;">6</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: center;">7</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="complément-à-2" class="level3" data-number="1.8.4">
<h3 data-number="1.8.4" class="anchored" data-anchor-id="complément-à-2"><span class="header-section-number">1.8.4</span> Complément à 2</h3>
<p>Dans le système de complément à un, la valeur 0 a deux représentations : « +0 » et « -0 » (exemple sur 4 bits: 0000 et 1111), ce qui oblige à réaliser deux tests pour tester la valeur nulle d’un résultat. Afin de pallier ce défaut, on a introduit la représentation par complément à deux.</p>
<p>On obtient le complément à deux en ajoutant 1 au complément à un. On ignore alors la retenue sur le bit de poids fort.</p>
<p>Le complément à deux ne s’applique qu’à des nombres ayant tous la même longueur : avec un codage sur <span class="math inline">\(n\)</span> bits, cette méthode permet de représenter toutes les valeurs entières de <span class="math inline">\(−2^n − 1\)</span> à <span class="math inline">\(2^{n − 1} − 1\)</span>.</p>
<p>Tous les entiers en <code>Python</code> sont représentés en complémentation à deux et avec un nombre <em>infini</em> de bits (la limite est la capacité de mémoire de votre système). Par exemple:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sys <span class="im">import</span> getsizeof</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>counter1 <span class="op">=</span> <span class="dv">0</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>counter2 <span class="op">=</span> <span class="dv">100</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>counter3 <span class="op">=</span> <span class="dv">2</span><span class="op">**</span><span class="dv">64</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>size1 <span class="op">=</span> getsizeof(counter1)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>size2 <span class="op">=</span> getsizeof(counter2)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>size3 <span class="op">=</span> getsizeof(counter3)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(size1, size2, size3)</span></code><button title="Copiez au Presse-Papier" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>24 28 36</code></pre>
</div>
</div>
<section id="remarques" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="remarques">Remarques</h4>
<p>Dans la représentation en complément à deux:</p>
<ul>
<li>le bit de gauche est réservé au signe;</li>
<li>les <strong>entiers négatifs</strong> sont représentés par leur complément à deux;</li>
<li>les entiers positifs sont simplement représentés par leur nombre binaire signé;</li>
<li>le nombre de bits est <strong>fixé</strong>.</li>
</ul>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il n’est pas nécessaire de complémenter un nombre positif.</p>
</div>
</div>
<p>La complémentation à deux se fait en trois étapes:</p>
<ol type="1">
<li>Écrivez le nombre binaire sur le nombre de bits préalablement établi en ne tenant pas compte du signe (ajoutez des 0 à gauche au besoin).</li>
<li>Calculez le complément à un (<strong>Remplacez tous les <code>0</code> par des <code>1</code> et tous les <code>1</code> par des <code>0</code></strong>).</li>
<li>Calculez le complément à deux (<strong>Ajoutez 1 au complément à un</strong>).</li>
</ol>
<div id="exm-nombre-moins-4-complement-deux" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.24 </strong></span>Écrivez le nombre <span class="math inline">\(M=-4\)</span> dans sa représentation en complément à deux.</p>
</div>
<div id="exm-complement-deux-octets" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.25 </strong></span>Trouvez les compléments à deux des octets suivants.</p>
<ol type="a">
<li>(0110 0100)</li>
<li>(0110 1101)</li>
<li>(0110 1001)</li>
</ol>
</div>
<div id="exm-valeur-5-8-bits" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.26 </strong></span>Vous avez 8 bits.</p>
<ol type="a">
<li>Écrivez 5 en binaire sur 8 bits.</li>
<li>Complémentez à deux la réponses précédente.</li>
<li>Additionnez les réponses obtenues en a) et en b).</li>
</ol>
</div>
</section>
</section>
<section id="addition-de-nombres-par-complémentation-à-deux" class="level3" data-number="1.8.5">
<h3 data-number="1.8.5" class="anchored" data-anchor-id="addition-de-nombres-par-complémentation-à-deux"><span class="header-section-number">1.8.5</span> Addition de nombres par complémentation à deux</h3>
<p>Puisque les opérations internes de l’ordinateur ne permettent que l’addition, il faut troiver une manière d’effectuer une soustraction sans réellement en faire une. Par exemple, afin de calculer 10-4, il est possible de faire l’addition 10+(-4).</p>
<p>Ainsi, le complément à deux est nécessaire pour représenter les nombres négatifs et pour effectuer des soustractions.</p>
<div class="callout-important callout callout-style-default callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<p>Il est important de notes que:</p>
<ul>
<li>Il faut utiliser des nombres signés;</li>
<li>Pour deux nombres ayant le même nombre de bits, il se peut que le résultat de l’addition de ces nombres comporte un bit de plus. Dans ce cas, il faut ignorer le bit supplémentaire;</li>
<li><strong>Si le signe de la réponses n’a pas de sens, cela signifie que le résultat de l’addition est un nombre trop grand pour la capacité de l’ordinateur, on parle alors de débordement.</strong></li>
<li>Si le bit-signe est à <code>1</code>, on doit complémenter le nombre pour retrouver le nombre négatif qui représente la réponse.</li>
</ul>
</div>
</div>
<section id="addition-de-deux-nombres-de-mêmes-signes" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="addition-de-deux-nombres-de-mêmes-signes">Addition de deux nombres de mêmes signes</h4>
<p><strong>Cas particuliers</strong>:</p>
<ul>
<li>Si, après l’addition, le bit-signe est le même que les deux chiffres, le résultat est correct.</li>
<li>Si le bit-signe est <em>différent</em> de celui des deux chiffres additionnés, il y a <strong>débordement</strong>.</li>
</ul>
<div id="exm-addition-complement-deux-1" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.27 </strong></span>À l’aide de la complémentation à deux, calculez 49+25.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="systeme_numeration_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div id="exm-addition-complement-deux-2" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.28 </strong></span>À l’aide de la complémentation à deux, calculez 75+87.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="systeme_numeration_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div id="exm-addition-complement-deux-3" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.29 </strong></span>À l’aide de la complémentation à deux, calculez -64-56.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="systeme_numeration_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div id="exm-addition-complement-deux-4" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.30 </strong></span>À l’aide de la complémentation à deux, calculez -78-85.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="systeme_numeration_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</section>
<section id="addition-de-deux-nombres-de-signes-différents" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="addition-de-deux-nombres-de-signes-différents">Addition de deux nombres de signes différents</h4>
<ul>
<li>Il n’y a aucun débordement possible (<strong>POURQUOI?</strong>)</li>
<li>Le résultat peut être positif ou négatif selon la valeur du bit-signe.</li>
<li>On complémente le résultat si le bit-signe est <code>1</code>.</li>
</ul>
<div id="exm-addition-complement-deux-5" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.31 </strong></span>À l’aide de la complémentation à deux, calculez -59-18.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="systeme_numeration_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
<div id="exm-addition-complement-deux-6" class="theorem example">
<p><span class="theorem-title"><strong>Exemple 1.32 </strong></span>À l’aide de la complémentation à deux, calculez 18-59.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="systeme_numeration_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</div>
</section>
</section>
<section id="opérateurs-bit-à-bit" class="level3" data-number="1.8.6">
<h3 data-number="1.8.6" class="anchored" data-anchor-id="opérateurs-bit-à-bit"><span class="header-section-number">1.8.6</span> Opérateurs bit à bit</h3>
<p>En logique, une opération bit à bit est un calcul manipulant les données directement au niveau des bits, selon une arithmétique booléenne. Elles sont utiles dès qu’il s’agit de manipuler les données à bas niveau : codages, couches basses du réseau (par exemple TCP/IP), cryptographie, etc.</p>
<p>Les opérations bit à bit courantes comprennent des opérations logiques bit par bit et des opérations de décalage des bits, vers la droite ou vers la gauche.</p>
</section>
<section id="left-shift" class="level3" data-number="1.8.7">
<h3 data-number="1.8.7" class="anchored" data-anchor-id="left-shift"><span class="header-section-number">1.8.7</span> LEFT-SHIFT &lt;&lt;</h3>
</section>
<section id="right-shift" class="level3" data-number="1.8.8">
<h3 data-number="1.8.8" class="anchored" data-anchor-id="right-shift"><span class="header-section-number">1.8.8</span> RIGHT-SHIFT &gt;&gt;</h3>
</section>
<section id="complément-à-un-même-chose-que-not" class="level3" data-number="1.8.9">
<h3 data-number="1.8.9" class="anchored" data-anchor-id="complément-à-un-même-chose-que-not"><span class="header-section-number">1.8.9</span> COMPLÉMENT À UN ~ (MÊME CHOSE QUE NOT)</h3>
</section>
</section>
<section id="représentation-des-nombres-en-virgule-flottante" class="level2" data-number="1.9">
<h2 data-number="1.9" class="anchored" data-anchor-id="représentation-des-nombres-en-virgule-flottante"><span class="header-section-number">1.9</span> Représentation des nombres en virgule flottante</h2>
<section id="la-norme-ieee754" class="level3" data-number="1.9.1">
<h3 data-number="1.9.1" class="anchored" data-anchor-id="la-norme-ieee754"><span class="header-section-number">1.9.1</span> La norme IEEE754</h3>
<p>En informatique, l’IEEE 754 est une norme sur l’arithmétique à virgule flottante mise au point par le <em>Institute of Electrical and Electronics Engineers</em>. Elle est la norme la plus employée actuellement pour le calcul des nombres à virgule flottante avec les CPU et les FPU. La norme définit les formats de représentation des nombres à virgule flottante (signe, mantisse, exposant, nombres dénormalisés) et valeurs spéciales (infinis et NaN), en même temps qu’un ensemble d’opérations sur les nombres flottants. Il décrit aussi cinq modes d’arrondi et cinq exceptions (comprenant les conditions dans lesquelles une exception se produit, et ce qui se passe dans ce cas).</p>
<section id="format-général" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="format-général">Format général</h4>
<p>Un nombre flottant est formé de trois éléments : la mantisse, l’exposant et le signe. Le bit de poids fort est le bit de signe : si ce bit est à 1, le nombre est négatif, et s’il est à 0, le nombre est positif. Les <span class="math inline">\(e\)</span> bits suivants représentent l’exposant biaisé (sauf valeur spéciale), et les <span class="math inline">\(m\)</span> bits suivants (<span class="math inline">\(m\)</span> bits de poids faible) représentent la mantisse.</p>
<div>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/2/29/IEEE754_Format_General.png" class="img-fluid figure-img"></p>
<p></p><figcaption class="figure-caption">Format général d’un nombre en virgule flottante.</figcaption><p></p>
</figure>
</div>
</div>
<p>L’exposant peut être positif ou négatif. Cependant, la représentation habituelle des nombres signés (complément à 2) rendrait la comparaison entre les nombres flottants un peu plus difficile. Pour régler ce problème, l’exposant est « biaisé », afin de le stocker sous forme d’un nombre non signé.</p>
<p>Ce biais est de 2e−1 − 1 (e représente le nombre de bits de l’exposant) ; il s’agit donc d’une valeur constante une fois que le nombre de bits e est fixé.</p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copié!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copié!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation column-body">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Préface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./logique.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Logique</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>